import {
  ShieldCheck,
  Building2,
  Building,
  Wrench,
  Calculator,
  HeadsetIcon,
  Truck,
  BarChart3,
  BadgeDollarSign,
  ShoppingBag,
  HeartHandshake,
  UserCheck,
  HelpingHand,
  CheckCircle2,
  XCircle,
  PauseCircle,
  CircleDot,
  Package,
  Wrench as WrenchIcon,
  ArrowUpCircle,
  Users,
  Building as BuildingIcon,
  Clock,
  Clock1 as ClockIcon,
  Box,
  CheckCircle,
  AlertCircle,
  XCircle as XCircleIcon,
  FileText,
  ClipboardList,
  Receipt,
  Truck as TruckIcon,
  FileSpreadsheet,
  Component,
  Image,
  Home,
  Warehouse,
  CircleDollarSign,
  CircleOff,
  Snowflake,
  LucideWrench,
  CircleCheck,
  DollarSign,
  Settings,
  MessageCircle,
  MessagesSquare,
} from "lucide-react";

export const getRoleOptions = [
  { value: "administrator", label: "Administrator", icon: ShieldCheck },
  { value: "general-manager", label: "General Manager", icon: Building2 },
  { value: "branch-manager", label: "Branch Manager", icon: Building },
  { value: "technician", label: "Technician", icon: Wrench },
  { value: "accountant", label: "Accountant", icon: Calculator },
  { value: "receptionist", label: "Receptionist", icon: HeadsetIcon },
  { value: "driver", label: "Driver", icon: Truck },
  { value: "sales-manager", label: "Sales Manager", icon: BarChart3 },
  { value: "sales-executive", label: "Sales Executive", icon: BadgeDollarSign },
  { value: "sales-assistant", label: "Sales Assistant", icon: ShoppingBag },
  { value: "cso", label: "CSO", icon: HeartHandshake },
  { value: "csr", label: "CSR", icon: UserCheck },
  { value: "helper", label: "Helper", icon: HelpingHand },
];

export const StatusOptions = [
  {
    value: "active",
    label: "Active",
    color: "255, 159, 67",
    icon: CheckCircle2,
  },
  { value: "inactive", label: "Inactive", color: "234, 84, 85", icon: XCircle },
  { value: "paused", label: "Paused", color: "234, 84, 85", icon: PauseCircle },
];

export const ComplaintStatusOptions = [
  { value: "open", label: "Open", color: "255, 159, 67", icon: CircleDot },
  {
    value: "assigned-to-technician",
    label: "Assigned to Technician",
    color: "234, 84, 85",
    icon: UserCheck,
  },
  {
    value: "part-demand",
    label: "Part Demand",
    color: "234, 84, 85",
    icon: Package,
  },
  {
    value: "done-by-technition",
    label: "Done by Technition",
    color: "234, 84, 85",
    icon: WrenchIcon,
  },
  {
    value: "service-lifting",
    label: "Service Lifting",
    color: "46, 204, 113",
    icon: ArrowUpCircle,
  },
  {
    value: "party-lifting",
    label: "Party Lifting",
    color: "52, 152, 219",
    icon: Users,
  },
  {
    value: "unit-in-service-center",
    label: "Unit in Service Center",
    color: "155, 89, 182",
    icon: BuildingIcon,
  },
  {
    value: "installation-pending",
    label: "Installation Pending",
    color: "230, 126, 34",
    icon: Clock,
  },
  {
    value: "in-progress",
    label: "In Progress",
    color: "241, 196, 15",
    icon: ClockIcon,
  },
  { value: "delivered", label: "Delivered", color: "26, 188, 156", icon: Box },
  {
    value: "close-pending-by-brand",
    label: "Closing Pending by Brand",
    color: "231, 76, 60",
    icon: AlertCircle,
  },
  {
    value: "feedback-pending",
    label: "Feedback Pending",
    color: "149, 165, 166",
    icon: Clock,
  },
  {
    value: "completed",
    label: "Completed",
    color: "39, 174, 96",
    icon: CheckCircle,
  },
  {
    value: "amount-pending",
    label: "Amount Pending",
    color: "234, 84, 85",
    icon: AlertCircle,
  },
  {
    value: "closed",
    label: "Closed",
    color: "41, 128, 185",
    icon: CheckCircle,
  },
  {
    value: "cancelled",
    label: "Cancelled",
    color: "192, 57, 43",
    icon: XCircleIcon,
  },
];

export const warrantyTypeOptions = [
  { value: "warrenty-card", label: "Warrenty Card", icon: FileText },
  { value: "jobsheet", label: "Jobsheet", icon: ClipboardList },
  { value: "invoice", label: "Invoice", icon: Receipt },
  { value: "delivery-challan", label: "Delivery Challan", icon: TruckIcon },
  { value: "service-challan", label: "Service Challan", icon: FileSpreadsheet },
  { value: "defective-part", label: "Defective Part", icon: Component },
  { value: "defective-picture", label: "Defective Picture", icon: Image },
  { value: "indoor", label: "Indoor", icon: Home },
  { value: "outdoor", label: "Outdoor", icon: Warehouse },
  { value: "ind-sr", label: "Ind-SR", icon: CircleDollarSign },
  { value: "out-sr", label: "Out-SR", icon: CircleOff },
];

export const complaintTypeOptions = [
  {
    value: "new-ac-free-installation",
    label: "New AC Free Installation",
    icon: Snowflake,
  },
  {
    value: "old-ac-free-installation",
    label: "Old AC Free Installation",
    icon: LucideWrench,
  },
  {
    value: "old-c/o-free-installation",
    label: "Old C/O Free Installation",
    icon: CircleCheck,
  },
  {
    value: "old-c/o-installation",
    label: "Old C/O Installation",
    icon: Settings,
  },
  { value: "free-installation", label: "Free Installation", icon: CircleCheck },
  { value: "paid-installation", label: "Paid Installation", icon: DollarSign },
  { value: "warranty", label: "Warranty", icon: ShieldCheck },
  { value: "revenue", label: "Revenue", icon: CircleDollarSign },
  { value: "service", label: "Service", icon: WrenchIcon },
  { value: "warrenty-revenue", label: "Warrenty+Revenue", icon: DollarSign },
  { value: "other", label: "Other", icon: CircleDot },
];

export const MessageTypeOptions = [
  {
    value: "auto_pay_reminder_2",
    label: "Update Complaint",
    icon: MessageCircle,
  },
  {
    value: "complaint_create_template",
    label: "Complaint Create Template",
    icon: MessagesSquare,
  },
];
